trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/*.tf"
    exclude:
      - README.md

# resources:
#   repositories:
#     - repository: .azuredevops
#       type: github
#       endpoint: KrijnvanderBurg
#       ref: main
#       name: KrijnvanderBurg/.azuredevops


extends:
  template: /.azuredevops/v1/pipelines/opentofu.yml
  parameters:
    openTofuDir: $(Build.Repository.LocalPath)/dataplatform-tf/
