trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/*.tf"
    exclude:
      - README.md

resources:
  repositories:
    - repository: .azuredevops
      type: github
      endpoint: KrijnvanderBurg
      ref: main
      name: KrijnvanderBurg/.azuredevops

extends:
  template: /v1/templates/stages/opentofu/validate_and_plan.yml@.azuredevops
  parameters:
    openTofuDir: $(Build.Repository.LocalPath)/dataplatform-tf/
