trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/*.tf"
    exclude:
      - README.md

extends:
  template: /.azuredevops/v1/pipelines/opentofu/validate_and_plan.yml
  parameters:
    openTofuDir: $(Build.Repository.LocalPath)/dataplatform-tf/
