trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "**/*.tf"
    exclude:
      - README.md

resources:
  repositories:
    - repository: .azuredevops
      type: github
      endpoint: KrijnvanderBurg
      ref: main
      name: KrijnvanderBurg/.azuredevops

extends:
  template: /v1/pipelines/opentofu.yml@.azuredevops
  parameters:
    openTofuDir: $(Build.Repository.LocalPath)/environments/dev/
    openTofuPlanFilepath: plan.out
  